export { default as Hero } from './Hero';
export { About } from './About';
export { Skills } from './Skills';
export { default as ContentBoxes } from './ContentBoxes';
export { Journey } from './Journey';
export { Qualifications } from './Qualifications';
export { Gallery } from './Gallery';
export { Blog } from './Blog';
export { CubingContent } from './CubingContent';
export { FunFacts } from './FunFacts';
export { FutureGoals } from './FutureGoals';
export { Testimonials } from './Testimonials';